<footer>
	<div class="container join">
		<p>Csatlakozz hozzánk Facebookon is!</p>
		<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="89" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>
	</div>
	<section class="container">
		<p>Ha bármilyen kérdésed vagy problémád felmerülne a feltöltéssel vagy a promócióval kapcsolatban, kérlek írj nekünk az alábbi e-mail címre: <a href="mailto:email@email.com">email@email.com</a></p>
	</section>
</footer>
<div id="fb-root"></div>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
	(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
	function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
	e=o.createElement(i);r=o.getElementsByTagName(i)[0];
	e.src='https://www.google-analytics.com/analytics.js';
	r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
	ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script>
</body>
</html>