<!DOCTYPE html>
<html lang="hu">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title></title>
        <meta name="description" content="">
        <!-- Favicons -->
        <!-- Screen CSS -->
        <link href="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/css/screen.css" rel="stylesheet">
        <!-- 3rd-party CSS -->
        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700,600&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- JQuery -->
        <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/3rd-party/jquery.min.js"></script>
        <!-- 3rd-party JS files -->
        
        <!-- Main JS file -->
        <script src="/<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/main.js"></script>
    </head>
    <body>
        <!--[if lt IE 9]>
        <p class="browserupgrade"><strong>Elavult</strong> böngészőt használsz. Kérlek <a href="http://browsehappy.com/">tölts le</a> újabb böngészőt, az optimális böngészés érdekében.</p>
        <![endif]-->
        <header>
            <div class="container">
                <a href="#" class="sony"></a>
                <a href="#" class="xperiax"></a>
            </div>
        </header>